---
- name: Install Tailscale
  ansible.builtin.import_tasks: install.yml

- name: Join the tailnet
  ansible.builtin.import_tasks: join.yml

- name: Validate the node
  ansible.builtin.import_tasks: validate.yml
